### ISSUE TITLE
Intercom / racks: Iveco, CV90, SISU, Bell. 

### ISSUE THREAD

**Issue by Tittoffer** [Tittoffer/NorwegianTaskForce#16]
Implementere Intercom og vehicle racks i egne kjøretøy. Mulig dette krever. I førsteomgang forsøk å legge til vehicle rack og evt. intercom i F16C(D) + Bell 412. Vurder så muligheten for å legge til Infantry phone til CV90 + SISU + M113. 

http://acre2.idi-systems.com/wiki/frameworks/vehicle-intercom

**Comment by TheMagnetar** [comment]
Please wait until the new intercom configuration.
https://github.com/IDI-Systems/acre2/pull/411

**Comment by Tittoffer** [comment]
That was actually the plan :)
