### ISSUE TITLE
Intercom i Iveco

### ISSUE THREAD

**Issue by sekkis** [Tittoffer/NorwegianTaskForce#6]
Ønsker intercom i Iveco

**Comment by Tittoffer** [comment]
Notert 👍 Har ikke tilgang til en åpen .pbo fil av ivecoen så får ikke gjort det nå. Så fort vi får den tilsendt skal jeg se på muligheten :)

**Comment by Tittoffer** [comment]
Funnet fnc i ACRE som kan åpne for denne muligheten uten kildefiler.

**Comment by Tittoffer** [comment]
Etter samtale med deler av stab har vi kommet frem til at Intercom i Iveco er unødvendig.
